### ISSUE TITLE
Incompatible dependencies

### ISSUE THREAD

**Issue by halixness** [vishaal27/SuS-X#6]
Hello, 
I've created a conda environment with python 3.6.8 as specified. Installing the dependencies as defined in your repository seems to fail:
```  
Collecting clip_retrieval==2.29.1
  Using cached clip_retrieval-2.29.1-py3-none-any.whl (332 kB)
Collecting diffusers==0.2.2
  Using cached diffusers-0.2.2-py3-none-any.whl (107 kB)
Collecting ftfy==6.0.3
  Using cached ftfy-6.0.3.tar.gz (64 kB)
Collecting numpy==1.18.3
  Using cached numpy-1.18.3-cp36-cp36m-manylinux1_x86_64.whl (20.2 MB)
Collecting openai==0.8.0
  Using cached openai-0.8.0.tar.gz (147 kB)
ERROR: Could not find a version that satisfies the requirement Pillow==9.3.0 (from versions: 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.4.0, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.8.0, 2.8.1, 2.8.2, 2.9.0, 3.0.0, 3.1.0rc1, 3.1.0, 3.1.1, 3.1.2, 3.2.0, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.4.0, 3.4.1, 3.4.2, 4.0.0, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.3.0, 5.0.0, 5.1.0, 5.2.0, 5.3.0, 5.4.0, 5.4.1, 6.0.0, 6.1.0, 6.2.0, 6.2.1, 6.2.2, 7.0.0, 7.1.0, 7.1.1, 7.1.2, 7.2.0, 8.0.0, 8.0.1, 8.1.0, 8.1.1, 8.1.2, 8.2.0, 8.3.0, 8.3.1, 8.3.2, 8.4.0)
ERROR: No matching distribution found for Pillow==9.3.0
```  
This happens also when using python 3.9 (as required by some packages):
```
Collecting clip_retrieval==2.29.1 (from -r requirements.txt (line 1))                               
  Using cached clip_retrieval-2.29.1-py3-none-any.whl (332 kB)                                      
Collecting diffusers==0.2.2 (from -r requirements.txt (line 2))                                     
  Using cached diffusers-0.2.2-py3-none-any.whl (107 kB)                                            
Collecting ftfy==6.0.3 (from -r requirements.txt (line 3))                                          
  Using cached ftfy-6.0.3.tar.gz (64 kB)                                                            
  Preparing metadata (setup.py) ... done                                                            
Collecting numpy==1.18.3 (from -r requirements.txt (line 4))                                        
  Using cached numpy-1.18.3.zip (5.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      Running from numpy source directory.
      <string>:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      /tmp/pip-install-vk8g3bjz/numpy_bcb5d83ee16b45ee904f3af51beee127/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.14')
      /tmp/pip-install-vk8g3bjz/numpy_bcb5d83ee16b45ee904f3af51beee127/tools/cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          def __init__(self, seed=None):
              BitGenerator.__init__(self, seed)
              self.rng_state.pcg_state = &self.pcg64_random_state
      
              self._bitgen.state = <void *>&self.rng_state
              self._bitgen.next_uint64 = &pcg64_uint64
                                         ^
      ------------------------------------------------------------
      
      _pcg64.pyx:113:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'uint64_t (void *) except? -1 nogil'.
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_pcg64.pyx
      Traceback (most recent call last):
        File "/tmp/pip-install-vk8g3bjz/numpy_bcb5d83ee16b45ee904f3af51beee127/tools/cythonize.py", line 238, in <module>
          main()
        File "/tmp/pip-install-vk8g3bjz/numpy_bcb5d83ee16b45ee904f3af51beee127/tools/cythonize.py", line 234, in main
          find_process_files(root_dir)
        File "/tmp/pip-install-vk8g3bjz/numpy_bcb5d83ee16b45ee904f3af51beee127/tools/cythonize.py", line 225, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/tmp/pip-install-vk8g3bjz/numpy_bcb5d83ee16b45ee904f3af51beee127/tools/cythonize.py", line 191, in process
          processor_function(fromfile, tofile)
        File "/tmp/pip-install-vk8g3bjz/numpy_bcb5d83ee16b45ee904f3af51beee127/tools/cythonize.py", line 80, in process_pyx
          subprocess.check_call(
        File "/home/xxxxx.xxxxxxxx/miniconda3/envs/susx/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/xxxxx.xxxxxxxx/miniconda3/envs/susx/bin/python', '-m', 'cython', '-3', '--fast-fail', '-o', '_pcg64.c', '_pcg64.pyx']' returned non-zero exit status 1.
      Cythonizing sources
      Traceback (most recent call last):
        File "/home/xxxxx.xxxxxxxx/miniconda3/envs/susx/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/xxxxx.xxxxxxxx/miniconda3/envs/susx/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/xxxxx.xxxxxxxx/miniconda3/envs/susx/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-f2r6x_65/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-f2r6x_65/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-f2r6x_65/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 488, in <module>
        File "<string>", line 469, in setup_package
        File "<string>", line 275, in generate_cython
      RuntimeError: Running cythonize failed!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: There was an error checking the latest version of pip.
```  
Could you provide us with an updated requirements file or more details on the env for reproducibility? Thank you.

**Comment by vishaal27** [comment]
Hey, thanks for your interest!

I think any Pillow version should work in principle. Perhaps, some of these dependencies have gotten deprecated over the past year---I just replicated the env with this, could you please check:

```bash
conda create -n test python=3.8 -y
conda activate test
pip install clip_retrieval==2.29.1 diffusers ftfy numpy openai Pillow regex setuptools torch torchvision tqdm
```

**Comment by halixness** [comment]
Thank you for answering promptly. With this setup I report a few changes that allowed to run the experiments: in `generate_sd_sus.py`:
```
     prompt = generate_prompt_array(args, class_name, batch_size, gpt3_prompts)
     generator = torch.Generator("cuda").manual_seed(batch_ind) 
++   pipe = pipe.to("cuda")
++   images = pipe(prompt, guidance_scale=args.guidance_scale, num_inference_steps=args.num_inference_steps, generator=generator).images
--   images = pipe(prompt, guidance_scale=args.guidance_scale, num_inference_steps=args.num_inference_steps, generator=generator)["sample"]
```
Moreover:
- Default `batch_size` is 5, so `num_images` shall be larger.
- In running `tipx.py`, I set `--text_prompt_type ensemble` as the script `generate_text_classifier_weights.py` does not generate weights of the form `*_ptcombined.pt` (combined is the default param for `--text_prompt_type`). Is this normal in order to reproduce current results?

**Comment by vishaal27** [comment]
Thanks for your efforts in helping reproduce the numbers. For the `ptcombined`, the script for generating the text_classifier_weights is here: https://github.com/vishaal27/SuS-X/blob/main/run_cupl_baseline.py
Either ways, you can use `ptensemble`, `ptcupl` or `ptcombined` as the classifier weights. Note, our best results are obtained with `ptcombined`.

**Comment by halixness** [comment]
Thank you, that solved the issue and I obtained the expected scores. A confirmation on reproducing few-shot scores: few-shot features are generated on the train split; are these the ones used as support set when running `tipx.py`?

**Comment by vishaal27** [comment]
Yes exactly, the support set features are the ones generated from the train split. We then validate on the validation features (in some cases the validation is the same as the test as discussed in the paper), and then evaluate the final model on the test set. Please let me know if you have any other questions. Thanks!
